/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LatihanGUI;

/**
 *
 * @author WINDOWS 10
 */
public class Latihan2 extends javax.swing.JFrame {

    /**
     * Creates new form Latihan2
     */
    public Latihan2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TAhasil = new javax.swing.JTextArea();
        pilihanjurusan = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        varNama = new javax.swing.JTextField();
        varAbsen = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cbProgam = new javax.swing.JCheckBox();
        rdbTKJ = new javax.swing.JRadioButton();
        rdbRPL = new javax.swing.JRadioButton();
        cbDesing = new javax.swing.JCheckBox();
        cbAnimator = new javax.swing.JCheckBox();
        cbVideo = new javax.swing.JCheckBox();
        buttonSubmit = new javax.swing.JButton();
        buttonhapus = new javax.swing.JButton();
        buttonkeluar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TAHasil = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();

        TAhasil.setColumns(20);
        TAhasil.setRows(5);
        jScrollPane1.setViewportView(TAhasil);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Nama");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(47, 51, 50, 16);

        jLabel2.setText("Absen");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(47, 91, 35, 16);

        jLabel3.setText("Jurusan");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(47, 123, 44, 16);

        jLabel4.setText("Hobi");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(47, 184, 25, 16);
        getContentPane().add(varNama);
        varNama.setBounds(98, 48, 241, 22);
        getContentPane().add(varAbsen);
        varAbsen.setBounds(100, 88, 239, 22);

        jLabel5.setFont(new java.awt.Font("Tekton Pro Ext", 1, 18)); // NOI18N
        jLabel5.setText("BIODATA");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(160, 13, 230, 19);

        cbProgam.setText("Progamming");
        cbProgam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbProgamActionPerformed(evt);
            }
        });
        getContentPane().add(cbProgam);
        cbProgam.setBounds(98, 180, 101, 25);

        rdbTKJ.setText("TKJ");
        getContentPane().add(rdbTKJ);
        rdbTKJ.setBounds(98, 123, 49, 25);

        rdbRPL.setText("RPL");
        rdbRPL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbRPLActionPerformed(evt);
            }
        });
        getContentPane().add(rdbRPL);
        rdbRPL.setBounds(165, 123, 49, 25);

        cbDesing.setText("Desinger");
        getContentPane().add(cbDesing);
        cbDesing.setBounds(98, 243, 79, 25);

        cbAnimator.setText("Animator");
        cbAnimator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAnimatorActionPerformed(evt);
            }
        });
        getContentPane().add(cbAnimator);
        cbAnimator.setBounds(252, 180, 81, 25);

        cbVideo.setText("Video editing");
        getContentPane().add(cbVideo);
        cbVideo.setBounds(252, 243, 103, 25);

        buttonSubmit.setText("Submit");
        buttonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSubmitActionPerformed(evt);
            }
        });
        getContentPane().add(buttonSubmit);
        buttonSubmit.setBounds(98, 319, 73, 25);

        buttonhapus.setText("Remove");
        buttonhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonhapusActionPerformed(evt);
            }
        });
        getContentPane().add(buttonhapus);
        buttonhapus.setBounds(252, 319, 79, 25);

        buttonkeluar.setText("Exit");
        buttonkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonkeluarActionPerformed(evt);
            }
        });
        getContentPane().add(buttonkeluar);
        buttonkeluar.setBounds(410, 319, 53, 25);

        jLabel6.setText("Hasil");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(98, 362, 73, 16);

        TAHasil.setColumns(20);
        TAHasil.setRows(5);
        jScrollPane2.setViewportView(TAHasil);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(140, 370, 350, 190);

        jLabel7.setForeground(new java.awt.Color(255, 102, 102));
        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\WINDOWS 10\\Pictures\\Saved Pictures\\wallpaper2you_111227.jpg")); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(-60, -100, 670, 680);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdbRPLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbRPLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbRPLActionPerformed

    private void cbProgamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbProgamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbProgamActionPerformed

    private void cbAnimatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAnimatorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbAnimatorActionPerformed

    private void buttonkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonkeluarActionPerformed
        // TODO add your handling code here:
        dispose();
        //System.exit(1);
    }//GEN-LAST:event_buttonkeluarActionPerformed

    private void buttonhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonhapusActionPerformed
        // TODO add your handling code here:
        
        varNama.setText("");
        varAbsen.setText("");
        cbProgam.setSelected(false);
        cbAnimator.setSelected(false);
        cbDesing.setSelected(false);
        cbVideo.setSelected(false);
    }//GEN-LAST:event_buttonhapusActionPerformed

    private void buttonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSubmitActionPerformed
        // TODO add your handling code here:
        
        String nama = varNama.getText();
        String absen = varAbsen.getText();
        String jurusan;
        String Hobi =" ";
        
        //untuk pilihan jurusan
        if (rdbRPL.isSelected())
            jurusan = "RPL";
        else if (rdbTKJ.isSelected())
            jurusan = "TKJ";
        else
            jurusan="";
        
        //untuk pilihan checkbox
        if (cbAnimator.isSelected())
            Hobi+=cbAnimator.getText()+", ";
      if (cbDesing.isSelected())
            Hobi+=cbDesing.getText()+", "; 
      if (cbProgam.isSelected())
            Hobi+=cbProgam.getText()+", ";
      if (cbVideo.isSelected())
            Hobi+=cbVideo.getText()+", ";
      
      //untuk hasil
      TAHasil.setText("Nama anda :" +nama+"\n Absen anda :"+absen
      +"\nJurusan anda:"+jurusan+"\nHobi anda"+Hobi);
    }//GEN-LAST:event_buttonSubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Latihan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Latihan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Latihan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Latihan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Latihan2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TAHasil;
    private javax.swing.JTextArea TAhasil;
    private javax.swing.JButton buttonSubmit;
    private javax.swing.JButton buttonhapus;
    private javax.swing.JButton buttonkeluar;
    private javax.swing.JCheckBox cbAnimator;
    private javax.swing.JCheckBox cbDesing;
    private javax.swing.JCheckBox cbProgam;
    private javax.swing.JCheckBox cbVideo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.ButtonGroup pilihanjurusan;
    private javax.swing.JRadioButton rdbRPL;
    private javax.swing.JRadioButton rdbTKJ;
    private javax.swing.JTextField varAbsen;
    private javax.swing.JTextField varNama;
    // End of variables declaration//GEN-END:variables
}
